config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  get 'projects/home'

  resources :projects do
    resources :tasks
  end
  resources :comments

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/project.rb
class Project < ActiveRecord::Base

belongs_to :user
has_many :tasks
 validates :name, length: {
    minimum: 3,
    maximum: 40,
    too_short: "must have at least %{count} characters",
    too_long: "must have at most %{count} characters"
       }
end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :project
  belongs_to :user

  validates :name, length: {
    minimum: 3,
    maximum: 40,
    too_short: "must have at least %{count} characters",
    too_long: "must have at most %{count} characters"
       }
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

         has_many :projects
         has_many :tasks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  def index
    @projects = current_user.projects
  end

  def show
    @project = Project.find(params[:id])
  end

  def projects_params
    params.require(:project).permit(:name)
  end

  def new
    @project = Project.new
  end

  def create
    @project = current_user.projects.new(projects_params)

    if @project.save
      redirect_to projects_path, :notice => " Your new project created! "
    else
      render "new"
    end
  end

  def edit
    @project = Project.find(params[:id])
  end

  def update
    @project = Project.find(params[:id])
    if @project.update_attributes(projects_params)
      redirect_to projects_path, :notice => " Your project updated! "
    else
      render "edit"
    end
  end

  def destroy
     @project = Project.find(params[:id])
     @project.destroy

     redirect_to projects_path, notice => "Your project was deleted!"
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  def new
    @task = Task.new
  end

  def create
    @project = Project.find(params[:project_id])
    @task = project.tasks.create
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ToDoListV2</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% flash.each do |name, message| %>
<%= content_tag :div, message, :id => "flash_#{name}" %>
  <% end %>

<%= yield %>

</body>
</html>

app/views/projects/edit.html.erb
<h1> This is ediefet pagsdse </h1>


<% @projects.each do |a| %>

<% end %>

app/views/projects/home.html.erb
<h1>Projects#home</h1>
<p>Find me in app/views/projects/home.html.erb</p>

app/views/projects/index.html.erb
<h1> This is Index <h1>

<% @projects = current_user.projects %>
  <% @projects.each do |project| %>
<p> <%= link_to project.name, project %> <p>
<%= link_to "New task", new_project_task_path(project) %>
<% end %>

<div class="btn-group" role="group" aria-label="...">
  <button type="button" class="btn btn-default"><%= link_to "New Project", new_project_path %></button>
    <button type="button" class="btn btn-default"><%= link_to 'Back', projects_path, id: "new_link", remote: true %></button>
</div>

app/views/projects/new.html.erb
<h1> This is New page </h1>

<%= form_for @project do |p| %>
  <%= p.label :name %> : <%= p.text_field :name %>
  <%= p.submit "Add" %>

  <% end %>

app/views/projects/new.js.erb
$('#new_link').hide().after('ewrewrew')

app/views/projects/show.html.erb
<h1> <%= @project.name %> </h1>




<%= link_to 'Back', projects_path %>